# Generated by Django 4.1.7 on 2023-06-28 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_delete_hotelimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('upadate_at', models.DateField(auto_now_add=True)),
                ('images', models.ImageField(upload_to='hotel')),
                ('more_img', models.ImageField(upload_to='hotel')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
