# Generated by Django 4.1.7 on 2023-06-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotelimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelImages',
        ),
    ]
