# Generated by Django 4.1.7 on 2023-06-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotelimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='userImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(upload_to='user_img')),
            ],
        ),
    ]
