# Generated by Django 4.1.7 on 2023-06-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_rename_user_img_userimg_userimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userImg',
        ),
    ]
