# Generated by Django 4.1.7 on 2023-07-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
