# Generated by Django 4.1.7 on 2023-07-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
